<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Administrators</h4>
                <p class="category">Add, Edit or Remove administrator accounts</p>
                <a href="#" rel="tooltip" title="" class="btn btn-success btn-simple btn-xs" data-original-title="Create New">
                    <i class="fa fa-user"></i>
                </a>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Actions</th>
                            <th>User Name</th>
                            <th>Full Name</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-center">1</td>
                            <td class="td-actions">
                                <a href="#" rel="tooltip" title="" class="btn btn-warning btn-simple btn-xs" data-original-title="Edit Profile">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                            <td>admin</td>
                            <td>Rolf Bansbach</td>
                            <td>rolf@softecdigital.com</td>
                            
                        </tr>
                        <tr>
                            <td class="text-center">2</td>
                            <td class="td-actions">
                                <a href="#" rel="tooltip" title="" class="btn btn-warning btn-simple btn-xs" data-original-title="Edit Profile">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="#" rel="tooltip" title="" class="btn btn-danger btn-simple btn-xs" data-original-title="Remove">
                                    <i class="fa fa-times"></i>
                                </a>
                            </td>
                            <td>esteban</td>
                            <td>Esteban Robles</td>
                            <td>esteban@softecdigital.com</td>
                            
                        </tr>
                        <tr>
                            <td class="text-center">3</td>
                            <td class="td-actions">
                                <a href="#" rel="tooltip" title="" class="btn btn-warning btn-simple btn-xs" data-original-title="Edit Profile">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="#" rel="tooltip" title="" class="btn btn-danger btn-simple btn-xs" data-original-title="Remove">
                                    <i class="fa fa-times"></i>
                                </a>
                            </td>
                            <td>ed.reyes</td>
                            <td>Edward Reyes</td>
                            <td>edward.reyes@softecdigital.com</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
